### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [cedobor/prj-rev-bwfs-dasmoto#2]
For properties shared among all your elements, such as `font-family: Helvetica;`, you could use `body` as your selector. Then, all of the `body` element's children elements would automatically inherit this property:

```css
body {
  font-family: Helvetica;
}
```
