### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [cedobor/prj-rev-bwfs-dasmoto#3]
Alternatively, you could use `h2` as the selector to specify properties shared among the 3 heading elements:

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/cedobor/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/style.css#L10-L16
https://github.com/cedobor/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/style.css#L25-L31
